version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: vishva
      POSTGRES_PASSWORD: vishva
      POSTGRES_DB: vishva
    volumes:
      - postgres-db:/var/lib/postgresql/data


volumes:
  postgres-db: